export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP = 'SIGN_UP'
export const TO_LOGIN = 'TO_LOGIN'
export const TO_SIGNUP = 'TO_SIGNUP'
export const SET_NAME = 'SET_NAME'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const DEL_ACCOUNT = 'DEL_ACCOUNT'

export const UPDATE_ORDER_DATA = 'UPDATE_ORDER_DATA'
export const SET_ORDER_DATA = 'SET_ORDER_DATA'
export const ADD_ORDER_DATA = 'ADD_ORDER_DATA'

export const ADD_FLIGHT_DATA = 'ADD_FLIGHT_DATA'
export const SET_FLIGHT_DATA = 'SET_FLIGHT_DATA'
export const SET_SEARCH_FLIGHT_FORM = 'SET_SEARCH_FLIGHT_FORM'
